### ISSUE TITLE
GUI Spiel Ende

### ISSUE THREAD

**Issue by dimitripy** [FishMacc/noScrabble#24]
Siegerehrung und Leaderboard

**Comment by JasWeimer** [comment]
Spiel-Ende-Seite erstellt, mit Nennung des Gewinners. Leaderboard nicht integriert, da es noch nicht fertig ist und vorher ohnehin permanent angezeigt werden soll und wir uns gegen eine erneute Anzeige auf der Ende-Seite entschieden haben.

**Comment by JasWeimer** [comment]
Ist inzwischen gemerged und funktioniert.
