### ISSUE TITLE
Wortverifizierung durch Bing

### ISSUE THREAD

**Issue by kiltz** [FishMacc/noScrabble#4]
Prüft bitte ob der REST-Service

https://learn.microsoft.com/de-de/xamarin/xamarin-forms/data-cloud/azure-cognitive-services/spell-check

zur Überprüfung der Wörter genutzt werden kann.

**Comment by dimitripy** [comment]
Wir haben keinen zuverlässigen Dienst gefunden, der kostenlos für uns geeignet ist. Unser Lösungsansatz besteht nun darin, aus einem lokalen Wörterbuch die Existenz des Wortes zu überprüfen.

**Comment by dimitripy** [comment]
Wir haben keinen zuverlässigen Dienst gefunden, der kostenlos für uns geeignet ist. Unser Lösungsansatz besteht nun darin, aus einem lokalen Wörterbuch die Existenz des Wortes zu überprüfen.
